plants:
    name-of-plant-in-flux-db:
      conduct:
        min: 300
        max: 800
      water:
        min: 50
        max: 80
      temp:
        min: 20
        max: 30
    second-name-of-plant-in-flux-db:
          conduct:
            min: 300
            max: 800
          water:
            min: 50
            max: 80
          temp:
            min: 20
            max: 30
